esphome:
  name: pico
  friendly_name: pico

esp32:
  board: pico32
  framework:
    type: arduino

# Enable logging
logger:
  logs:
    component: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: "y9OnnIrLwn1VSoycPmlr1BisM+W3lfF2v47eCBgFhgc="

ota:
  password: "ef2bc107da9d9db3c8f2e9a4f5a9e318"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pico Fallback Hotspot"
    password: "ZUJJZCd24seJ"

captive_portal:


# NTP时间服务器
time:
  - platform: homeassistant
    id: esptime
    timezone: Asia/Shanghai
            

#字体
font:
  - file: 'Roboto-Regular.ttf'
    id: font1
    size: 14

  - file: 'Roboto-Regular.ttf'
    id: font2
    size: 17

  - file: 'Roboto-Regular.ttf'
    id: font3
    size: 19

#启用I2C双总线通讯 管理各支路外设 
i2c:
  - id: bus_a # GPIO21 GPIO22
    sda: 21
    scl: 22
    scan: true
    frequency: 200kHZ
  
  - id: bus_b # GPIO32 GPIO33
    sda: 32
    scl: 33
    scan: true
    frequency: 200kHZ


# 温度 湿度 光照传感器
sensor:
  - platform: dht
    pin: GPIO26
    temperature:
      id: my_temp
      name: "Temperature"
    humidity:
      id: my_hum
      name: "Humidity"
    update_interval: 5s

  - platform: bh1750
    i2c_id: bus_b
    name: "Illuminance"
    address: 0x23
    update_interval: 5s

#OLED模块
display:
  - platform: ssd1306_i2c
    i2c_id: bus_a
    model: "SSD1306 128X64"
    address: 0x3c
    id: my_display
    pages:
      - id: page1
        lambda: |-
          it.print(it.get_width(), 0,id(font1), "Temperature");        
      - id: page2
        lambda: |-
          it.strftime(0, 0, id(font1), "%Y-%m-%d %H:%M:%S", id(esptime).now());

# 循环显示不同的页面
interval:
  - interval: 10s
    then:
      - display.page.show_next: my_display
      - component.update: my_display          

# NFC PN532 配置
pn532_i2c:
  update_interval: 1s
  i2c_id: bus_a

# 二进制传感器配置
binary_sensor:
  - platform: pn532
    id: NFC532
    uid: 74-10-37-94
    name: "PN532 NFC Tag"

# 开关配置
switch:
  - platform: gpio
    pin: 25
    name: "Living Room Dehumidifier"

# Status LED (Binary LED) 配置
light:
  - platform: binary
    name: "Status LED"
    output: light_output
    on_turn_on:
    - logger.log: "Light Turned On!"
    on_turn_off:
    - logger.log: "Light Turned Off!"

# 配置GPIO的输入输出功能
output:
  - id: light_output
    platform: gpio
    pin: GPIO1



    